# Generated by Django 3.0.8 on 2020-09-10 17:34

import classify.storage_backends
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dataset',
            field=models.FileField(storage=classify.storage_backends.PrivateMediaStorage(), upload_to='datasets/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])]),
        ),
    ]
