# Generated by Django 3.0.8 on 2020-08-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationmodel',
            name='trained_model',
            field=models.FileField(blank=True, null=True, upload_to='models/'),
        ),
    ]
