# Generated by Django 3.0.8 on 2020-08-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_classificationmodel_trained_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationmodel',
            name='test_acc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='classificationmodel',
            name='training_acc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
